{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "hCDRrUeYIU5j",
   "metadata": {
    "id": "hCDRrUeYIU5j"
   },
   "source": [
    "# Section 5.2: Swiss roll with density removal and dimension gating\n",
    "\n",
    "This notebook combines the input-data figure and the numerical experiment for\n",
    "the Swiss-roll subsection.  All code comments are in English."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "O1jU6L0KIU5m",
   "metadata": {
    "id": "O1jU6L0KIU5m"
   },
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Section 5.2: Swiss roll with density removal and dimension gating\n",
    "# Combined code for the input figure and the numerical experiment\n",
    "# ============================================================\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.colors import LinearSegmentedColormap\n",
    "from numpy.linalg import eigh\n",
    "from scipy.spatial.distance import pdist\n",
    "from sklearn.neighbors import NearestNeighbors\n",
    "from joblib import Parallel, delayed\n",
    "\n",
    "try:\n",
    "    import pandas as pd\n",
    "except ImportError:\n",
    "    pd = None\n",
    "\n",
    "\n",
    "# ---------------- Global settings ----------------\n",
    "N_MANIFOLD = 800\n",
    "T_LO, T_HI = 1.5 * np.pi, 4.5 * np.pi\n",
    "HEIGHT = 21.0\n",
    "\n",
    "# Clutter levels used in the numerical experiment.\n",
    "CLUTTER_LEVELS = [0, 50, 100, 200, 400]\n",
    "\n",
    "# Number of repetitions and parallel jobs.\n",
    "# Increase N_REP for the final run if needed.\n",
    "N_REP = 8\n",
    "N_JOBS = 7\n",
    "\n",
    "# Graph and local-dimension parameters.\n",
    "K_GRAPH = 15        # Number of nearest neighbors in the base graph\n",
    "K_H = 5             # Neighbor rank used to estimate the kernel bandwidth\n",
    "K_DIM = 20          # Maximum neighbor count used for local dimension estimation\n",
    "DIM_KS = [10, 15, 20]\n",
    "\n",
    "# Dimension-gate parameters.\n",
    "M0 = 2.0            # Intrinsic dimension of the clean Swiss roll\n",
    "ETA = 2.0           # Sharpness of the local-dimension gate\n",
    "\n",
    "# Diffusion-map parameters.\n",
    "R_EMB = 2           # Embedding dimension\n",
    "T_DIFF = 1.0        # Diffusion time\n",
    "\n",
    "# Figure settings.\n",
    "PLOT_SEED = 1400\n",
    "PLOT_CLUTTER = 400\n",
    "OUTDIR = \"gdc_figures\"\n",
    "os.makedirs(OUTDIR, exist_ok=True)\n",
    "\n",
    "EPS = 1e-12\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "RODkwhYGIU5n",
   "metadata": {
    "id": "RODkwhYGIU5n"
   },
   "outputs": [],
   "source": [
    "# ---------------- Data generation ----------------\n",
    "def arclength(t):\n",
    "    \"\"\"Compute the arc-length coordinate of the planar spiral r=t.\"\"\"\n",
    "    return 0.5 * (t * np.sqrt(1.0 + t * t) + np.arcsinh(t))\n",
    "\n",
    "\n",
    "def make_swiss(seed, n_manifold=N_MANIFOLD, return_parameters=False):\n",
    "    \"\"\"\n",
    "    Generate a clean Swiss roll in R^3.\n",
    "\n",
    "    The ground-truth intrinsic coordinates are (arc length, height), which are\n",
    "    used only for evaluating preservation of the manifold geometry.\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "    t = rng.uniform(T_LO, T_HI, n_manifold)\n",
    "    h = rng.uniform(0.0, HEIGHT, n_manifold)\n",
    "\n",
    "    X = np.column_stack([\n",
    "        t * np.cos(t),\n",
    "        h,\n",
    "        t * np.sin(t)\n",
    "    ])\n",
    "\n",
    "    truth = np.column_stack([arclength(t), h])\n",
    "\n",
    "    if return_parameters:\n",
    "        return X, truth, t, h\n",
    "    return X, truth\n",
    "\n",
    "\n",
    "def add_clutter(X, n_clutter, seed):\n",
    "    \"\"\"\n",
    "    Add uniform off-manifold clutter points in the bounding box of X.\n",
    "\n",
    "    The returned mask marks the original manifold points.  Evaluation is always\n",
    "    performed on the manifold points only, while the graph is built on all\n",
    "    points, including clutter.\n",
    "    \"\"\"\n",
    "    if n_clutter == 0:\n",
    "        return X.copy(), np.ones(len(X), dtype=bool), np.empty((0, X.shape[1]))\n",
    "\n",
    "    rng = np.random.default_rng(seed + 10_000)\n",
    "    lo, hi = X.min(axis=0), X.max(axis=0)\n",
    "    C = rng.uniform(lo, hi, size=(n_clutter, X.shape[1]))\n",
    "\n",
    "    Xall = np.vstack([X, C])\n",
    "    mask = np.zeros(len(Xall), dtype=bool)\n",
    "    mask[:len(X)] = True\n",
    "\n",
    "    return Xall, mask, C\n",
    "\n",
    "\n",
    "# ---------------- Graph construction and auxiliary quantities ----------------\n",
    "def base_kernel(Xall, h):\n",
    "    \"\"\"\n",
    "    Build a symmetric kNN Gaussian affinity matrix.\n",
    "\n",
    "    The same base graph is used by all methods; only the normalization or\n",
    "    gating step changes.\n",
    "    \"\"\"\n",
    "    nn = NearestNeighbors(n_neighbors=K_GRAPH + 1).fit(Xall)\n",
    "    dist, idx = nn.kneighbors(Xall)\n",
    "\n",
    "    n = len(Xall)\n",
    "    W = np.zeros((n, n))\n",
    "    weights = np.exp(-(dist[:, 1:] ** 2) / (2.0 * h * h))\n",
    "\n",
    "    for i in range(n):\n",
    "        W[i, idx[i, 1:]] = weights[i]\n",
    "\n",
    "    # Symmetrize the directed kNN graph.\n",
    "    W = np.maximum(W, W.T)\n",
    "    return W\n",
    "\n",
    "\n",
    "def bandwidth(Xman):\n",
    "    \"\"\"\n",
    "    Estimate a global bandwidth from the clean manifold scale.\n",
    "\n",
    "    This keeps the base kernel scale fixed across clutter levels.\n",
    "    \"\"\"\n",
    "    nn = NearestNeighbors(n_neighbors=K_H + 1).fit(Xman)\n",
    "    dist, _ = nn.kneighbors(Xman)\n",
    "    return np.median(dist[:, K_H])\n",
    "\n",
    "\n",
    "def local_dim(Xall):\n",
    "    \"\"\"\n",
    "    Estimate local intrinsic dimension by the Levina--Bickel MLE.\n",
    "\n",
    "    Several neighbor counts are averaged for stability.\n",
    "    \"\"\"\n",
    "    nn = NearestNeighbors(n_neighbors=K_DIM + 1).fit(Xall)\n",
    "    dist, _ = nn.kneighbors(Xall)\n",
    "\n",
    "    # Remove self-distances and protect against zero distances.\n",
    "    dist = np.maximum(dist[:, 1:], EPS)\n",
    "\n",
    "    estimates = []\n",
    "    for k2 in DIM_KS:\n",
    "        Tk = dist[:, k2 - 1][:, None]\n",
    "        logs = np.log(Tk / dist[:, :k2 - 1])\n",
    "        inv_dim = logs.sum(axis=1) / (k2 - 1)\n",
    "        estimates.append(1.0 / np.maximum(inv_dim, 1e-9))\n",
    "\n",
    "    return np.mean(estimates, axis=0)\n",
    "\n",
    "\n",
    "# ---------------- Diffusion embedding ----------------\n",
    "def diffusion_embed(W, r=R_EMB, t=T_DIFF):\n",
    "    \"\"\"\n",
    "    Compute the diffusion-map embedding from a symmetric affinity matrix.\n",
    "    \"\"\"\n",
    "    d = W.sum(axis=1) + EPS\n",
    "    sq = np.sqrt(d)\n",
    "\n",
    "    # Symmetric conjugate of the random-walk matrix.\n",
    "    S = W / sq[:, None] / sq[None, :]\n",
    "\n",
    "    val, vec = eigh(S)\n",
    "    order = np.argsort(val)[::-1]\n",
    "    val, vec = val[order], vec[:, order]\n",
    "\n",
    "    # Right eigenvectors of P = D^{-1} W.\n",
    "    phi = vec / sq[:, None]\n",
    "\n",
    "    # Remove the trivial eigenvector.\n",
    "    return phi[:, 1:1 + r] * (val[1:1 + r] ** t)\n",
    "\n",
    "\n",
    "# ---------------- Affinity transformations ----------------\n",
    "def affinity_DM(K, alpha):\n",
    "    \"\"\"\n",
    "    Coifman--Lafon alpha normalization.\n",
    "\n",
    "    alpha=1 removes the sampling-density drift in the usual diffusion-map\n",
    "    continuum limit.\n",
    "    \"\"\"\n",
    "    d = K.sum(axis=1) + EPS\n",
    "    return K / (d[:, None] ** alpha) / (d[None, :] ** alpha)\n",
    "\n",
    "\n",
    "def affinity_GD(K, q, gamma):\n",
    "    \"\"\"\n",
    "    Gamma-Dirichlet density gate based on the degree-density q.\n",
    "    \"\"\"\n",
    "    gate = (q[:, None] * q[None, :]) ** gamma\n",
    "    return gate * K\n",
    "\n",
    "\n",
    "def affinity_gate_then_DM(K, w, gamma):\n",
    "    \"\"\"\n",
    "    Counterexample order: apply the dimension gate first, then alpha=1.\n",
    "\n",
    "    The post-gate degree normalization can partially undo the clutter\n",
    "    suppression, so this order is included as a diagnostic contrast.\n",
    "    \"\"\"\n",
    "    C = ((w[:, None] * w[None, :]) ** gamma) * K\n",
    "    d_post = C.sum(axis=1) + EPS\n",
    "    return C / d_post[:, None] / d_post[None, :]\n",
    "\n",
    "\n",
    "def affinity_DG(K, w, gamma):\n",
    "    \"\"\"\n",
    "    Proposed dimension-gated affinity: alpha=1 density removal, then dimension gate.\n",
    "\n",
    "    The degree d removes sampling-density effects on the manifold, whereas the\n",
    "    independent gate w suppresses off-manifold clutter.\n",
    "    \"\"\"\n",
    "    d = K.sum(axis=1) + EPS\n",
    "    K_alpha = K / d[:, None] / d[None, :]\n",
    "    gate = (w[:, None] * w[None, :]) ** gamma\n",
    "    return gate * K_alpha\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "DnDKCOhoIU5n",
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 640
    },
    "id": "DnDKCOhoIU5n",
    "outputId": "7a1e7187-882b-43c6-dce2-faf2e8562b6c"
   },
   "outputs": [],
   "source": [
    "# ---------------- Figure: clean versus contaminated Swiss roll ----------------\n",
    "def truncate_colormap(cmap_name=\"viridis\", minval=0.05, maxval=0.78, n=256):\n",
    "    \"\"\"\n",
    "    Truncate a colormap to avoid the bright yellow end of viridis.\n",
    "    \"\"\"\n",
    "    cmap = plt.get_cmap(cmap_name)\n",
    "    return LinearSegmentedColormap.from_list(\n",
    "        f\"{cmap_name}_truncated\",\n",
    "        cmap(np.linspace(minval, maxval, n))\n",
    "    )\n",
    "\n",
    "\n",
    "def plot_clean_vs_clutter(\n",
    "    seed=PLOT_SEED,\n",
    "    n_clutter=PLOT_CLUTTER,\n",
    "    outdir=OUTDIR,\n",
    "    clutter_color=\"#cc00cc\",\n",
    "):\n",
    "    \"\"\"\n",
    "    Save the side-by-side input-data figure used in Section 5.2.\n",
    "    \"\"\"\n",
    "    Xman, truth, roll_t, height = make_swiss(seed, return_parameters=True)\n",
    "    Xall, mask, Xclutter = add_clutter(Xman, n_clutter, seed)\n",
    "\n",
    "    # Use common axis limits for the two panels.\n",
    "    mins = Xall.min(axis=0)\n",
    "    maxs = Xall.max(axis=0)\n",
    "    centers = (mins + maxs) / 2.0\n",
    "    radius = 0.5 * np.max(maxs - mins)\n",
    "\n",
    "    xlim = (centers[0] - radius, centers[0] + radius)\n",
    "    ylim = (centers[1] - radius, centers[1] + radius)\n",
    "    zlim = (centers[2] - radius, centers[2] + radius)\n",
    "\n",
    "    cmap_roll = truncate_colormap(\"viridis\", 0.05, 0.78)\n",
    "\n",
    "    fig = plt.figure(figsize=(11.0, 5.2))\n",
    "    axes = []\n",
    "    titles = [\n",
    "        \"(A) Clean Swiss roll\",\n",
    "        \"(B) Swiss roll with uniform clutter\",\n",
    "    ]\n",
    "\n",
    "    for panel in range(2):\n",
    "        ax = fig.add_subplot(1, 2, panel + 1, projection=\"3d\")\n",
    "        axes.append(ax)\n",
    "\n",
    "        sc = ax.scatter(\n",
    "            Xman[:, 0], Xman[:, 1], Xman[:, 2],\n",
    "            c=roll_t,\n",
    "            s=9,\n",
    "            cmap=cmap_roll,\n",
    "            alpha=0.92,\n",
    "            linewidths=0,\n",
    "            depthshade=False,\n",
    "        )\n",
    "\n",
    "        if panel == 1:\n",
    "            ax.scatter(\n",
    "                Xclutter[:, 0], Xclutter[:, 1], Xclutter[:, 2],\n",
    "                c=clutter_color,\n",
    "                s=13,\n",
    "                alpha=0.65,\n",
    "                linewidths=0,\n",
    "                depthshade=False,\n",
    "                label=\"uniform clutter\",\n",
    "            )\n",
    "            ax.legend(loc=\"upper left\", frameon=True, fontsize=8)\n",
    "\n",
    "        ax.set_title(titles[panel], pad=8)\n",
    "        ax.set_xlabel(r\"$x_1$\")\n",
    "        ax.set_ylabel(r\"$x_2$\")\n",
    "        ax.set_zlabel(r\"$x_3$\")\n",
    "\n",
    "        ax.set_xlim(*xlim)\n",
    "        ax.set_ylim(*ylim)\n",
    "        ax.set_zlim(*zlim)\n",
    "\n",
    "        ax.view_init(elev=18, azim=-65)\n",
    "\n",
    "        # Use faint pane backgrounds for a cleaner manuscript figure.\n",
    "        ax.xaxis.pane.set_alpha(0.05)\n",
    "        ax.yaxis.pane.set_alpha(0.05)\n",
    "        ax.zaxis.pane.set_alpha(0.05)\n",
    "\n",
    "    cbar = fig.colorbar(sc, ax=axes, shrink=0.72, pad=0.04, fraction=0.035)\n",
    "    cbar.set_label(r\"roll parameter $t$\")\n",
    "\n",
    "    fig.suptitle(\"Swiss roll data: clean and contaminated cases\", y=0.98)\n",
    "    plt.tight_layout(rect=[0.00, 0.00, 0.95, 0.96])\n",
    "\n",
    "    pdf_path = os.path.join(outdir, \"swiss_roll_clean_vs_clutter400_3d_magenta.pdf\")\n",
    "    png_path = os.path.join(outdir, \"swiss_roll_clean_vs_clutter400_3d_magenta.png\")\n",
    "\n",
    "    plt.savefig(pdf_path, bbox_inches=\"tight\")\n",
    "    plt.savefig(png_path, dpi=300, bbox_inches=\"tight\")\n",
    "    plt.show()\n",
    "\n",
    "    print(\"Saved:\", pdf_path)\n",
    "    print(\"Saved:\", png_path)\n",
    "\n",
    "    return pdf_path, png_path\n",
    "\n",
    "\n",
    "# Generate the manuscript figure.\n",
    "plot_clean_vs_clutter()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "CCGemPVBIU5o",
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "CCGemPVBIU5o",
    "outputId": "f1cc06b3-b5e7-4ac3-a590-652e1a405844"
   },
   "outputs": [],
   "source": [
    "# ---------------- Numerical experiment ----------------\n",
    "def geodesic_rho(coords, truth, mask):\n",
    "    \"\"\"\n",
    "    Correlate pairwise distances in the embedding with true manifold distances.\n",
    "\n",
    "    The correlation is computed only among the original manifold points.  Clutter\n",
    "    points affect the graph and the embedding, but are excluded from scoring.\n",
    "    \"\"\"\n",
    "    embedded_dist = pdist(coords[mask])\n",
    "    true_dist = pdist(truth)\n",
    "    return np.corrcoef(embedded_dist, true_dist)[0, 1]\n",
    "\n",
    "\n",
    "def one_run(n_clutter, seed):\n",
    "    \"\"\"\n",
    "    Run one Swiss-roll experiment for a fixed clutter level and random seed.\n",
    "    \"\"\"\n",
    "    Xman, truth = make_swiss(seed)\n",
    "    Xall, mask, _ = add_clutter(Xman, n_clutter, seed)\n",
    "\n",
    "    # The bandwidth is tied to the clean manifold scale.\n",
    "    h = bandwidth(Xman)\n",
    "\n",
    "    # The base graph is shared by all methods.\n",
    "    K = base_kernel(Xall, h)\n",
    "\n",
    "    # Degree-density used by GD.\n",
    "    q = K.sum(axis=1) / K.sum()\n",
    "\n",
    "    # Local-dimension gate used by DG.\n",
    "    m_hat = local_dim(Xall)\n",
    "    w_dim = np.exp(-ETA * np.maximum(m_hat - M0, 0.0))\n",
    "\n",
    "    out = {}\n",
    "    out[\"DM a=0\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_DM(K, 0.0)), truth, mask\n",
    "    )\n",
    "    out[\"DM a=1\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_DM(K, 1.0)), truth, mask\n",
    "    )\n",
    "    out[\"GD g=1.5\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_GD(K, q, 1.5)), truth, mask\n",
    "    )\n",
    "    out[\"GD g=2.5\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_GD(K, q, 2.5)), truth, mask\n",
    "    )\n",
    "    out[\"gate-then-DM g=1.5\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_gate_then_DM(K, w_dim, 1.5)), truth, mask\n",
    "    )\n",
    "    out[\"DG g=1.5\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_DG(K, w_dim, 1.5)), truth, mask\n",
    "    )\n",
    "    out[\"DG g=2.5\"] = geodesic_rho(\n",
    "        diffusion_embed(affinity_DG(K, w_dim, 2.5)), truth, mask\n",
    "    )\n",
    "\n",
    "    return n_clutter, out\n",
    "\n",
    "\n",
    "def run_experiment(\n",
    "    clutter_levels=CLUTTER_LEVELS,\n",
    "    n_rep=N_REP,\n",
    "    n_jobs=N_JOBS,\n",
    "    outdir=OUTDIR,\n",
    "):\n",
    "    \"\"\"\n",
    "    Run all repetitions and save a compact summary table.\n",
    "    \"\"\"\n",
    "    tasks = [\n",
    "        (n_clutter, 1000 * rep + n_clutter)\n",
    "        for n_clutter in clutter_levels\n",
    "        for rep in range(n_rep)\n",
    "    ]\n",
    "\n",
    "    results = Parallel(n_jobs=n_jobs)(\n",
    "        delayed(one_run)(n_clutter, seed) for n_clutter, seed in tasks\n",
    "    )\n",
    "\n",
    "    columns = [\n",
    "        \"DM a=0\",\n",
    "        \"DM a=1\",\n",
    "        \"GD g=1.5\",\n",
    "        \"GD g=2.5\",\n",
    "        \"gate-then-DM g=1.5\",\n",
    "        \"DG g=1.5\",\n",
    "        \"DG g=2.5\",\n",
    "    ]\n",
    "\n",
    "    agg = {c: {k: [] for k in columns} for c in clutter_levels}\n",
    "    for n_clutter, out in results:\n",
    "        for key in columns:\n",
    "            agg[n_clutter][key].append(out[key])\n",
    "\n",
    "    summary_rows = []\n",
    "    for n_clutter in clutter_levels:\n",
    "        row = {\"clutter\": n_clutter}\n",
    "        for key in columns:\n",
    "            values = np.asarray(agg[n_clutter][key])\n",
    "            row[f\"{key} mean\"] = values.mean()\n",
    "            row[f\"{key} sd\"] = values.std(ddof=0)\n",
    "        summary_rows.append(row)\n",
    "\n",
    "    if pd is not None:\n",
    "        summary = pd.DataFrame(summary_rows)\n",
    "        csv_path = os.path.join(outdir, \"swiss_roll_section52_results.csv\")\n",
    "        summary.to_csv(csv_path, index=False)\n",
    "        print(\"Saved:\", csv_path)\n",
    "    else:\n",
    "        summary = summary_rows\n",
    "\n",
    "    header = \"clutter | \" + \" | \".join(f\"{key:>20}\" for key in columns)\n",
    "    print(header)\n",
    "    print(\"-\" * len(header))\n",
    "\n",
    "    for n_clutter in clutter_levels:\n",
    "        entries = []\n",
    "        for key in columns:\n",
    "            values = np.asarray(agg[n_clutter][key])\n",
    "            entries.append(f\"{values.mean():6.3f}({values.std(ddof=0):.2f})\")\n",
    "        print(f\"{n_clutter:7d} | \" + \" | \".join(f\"{x:>20}\" for x in entries))\n",
    "\n",
    "    print()\n",
    "    print(\"Interpretation:\")\n",
    "    print(\"  gate-then-DM applies the dimension gate before alpha=1 normalization;\")\n",
    "    print(\"  this order can undo part of the clutter suppression.\")\n",
    "    print(\"  DG applies alpha=1 density removal first and the independent dimension\")\n",
    "    print(\"  gate second; this is the proposed density-removal-plus-gating order.\")\n",
    "\n",
    "    return summary\n",
    "\n",
    "\n",
    "# Run the numerical experiment.\n",
    "# This cell may take several minutes depending on the runtime.\n",
    "summary = run_experiment()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "hO4Xxf8uI0iS",
   "metadata": {
    "id": "hO4Xxf8uI0iS"
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "pygments_lexer": "ipython3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
